publicHoistPattern:
  - vitest
  - vite-node

shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^7.2.0
    '@commitlint/cli': ^20.4.1
    '@commitlint/config-conventional': ^20.4.1
    '@types/json-schema': ^7.0.15
    bumpp: ^10.4.0
    eslint: ^9.39.2
    husky: ^9.1.7
    lint-staged: ^16.2.7
    typescript: ^5.9.3
    unbuild: ^3.6.1
  test:
    '@vitest/browser-playwright': ^4.0.18
    '@vitest/coverage-v8': ^4.0.18
    playwright: ^1.58.1
    vitest: ^4.0.18

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

sideEffectsCache: false
strictPeerDependencies: false
