packages:
  - docs
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    husky: ^9.1.7
    lint-staged: ^16.2.0
    tsx: ^4.20.5
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vite: ^7.1.7
    vue-tsc: ^3.0.8
  test:
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    playwright: ^1.55.1
    vitest: ^3.2.4
    vitest-browser-vue: ^1.1.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

shamefullyHoist: true
shellEmulator: true
sideEffectsCache: false
strictPeerDependencies: false
