packages:
  - docs
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    bumpp: ^10.2.3
    eslint: ^9.37.0
    husky: ^9.1.7
    lint-staged: ^16.2.3
    tsx: ^4.20.6
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.1.9
    vue-tsc: ^3.1.0
  test:
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    playwright: ^1.55.1
    vitest: ^3.2.4
    vitest-browser-vue: ^1.1.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

shamefullyHoist: true
shellEmulator: true
sideEffectsCache: false
strictPeerDependencies: false
publicHoistPattern:
  - vitest
  - vitest-browser-vue
  - vite-node
